Region: kr-standard
AccessKeyID: AB91FBC33D88781FB159
SecretKey: C93B6C02EE7C750AF68F7B8A55EBDBCC36E16E53
EndPoint: https://kr.object.ncloudstorage.com
Bucket: epicrocket
ObjectRoot: SProject
DownloadPath: D:\SUB\SProject