version: '3'
services:
  horde_storage:
    build:
      context: "../../../../"
      dockerfile: Programs/Horde/HordeStorage/dockerfile
      args:
        Project: Horde.Storage
    ports:
    - "58001:80" 
    - "58002:8080" 
    networks:
    - network_cache_bridge
    environment:
    - HORDESTORAGE_MODE=Cache
    - Jupiter__CurrentSite=docker-compose-cache
    - Serilog__MinimumLevel__Default=Debug
    - CORECLR_ENABLE_PROFILING=0
    - Mongo__ConnectionString=mongodb://root:mongo_root_passwd@mongo
    - Filesystem__RootDir=/data/blob-store
    - Upstream__ConnectionString=https://jupiter.devtools-dev.epicgames.com
    - Auth__Method=Disabled
    - Namespaces__Policies__*__Claims=*
    links:
    - mongo
    volumes:
    - horde-storage-volume:/data/blob-store
    labels:
      com.datadoghq.ad.logs: '[{"source":"csharp", "service": "horde-storage"}]'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo_root_passwd
    ports:
    - "58000:27017" 
    networks:
    - network_cache_bridge
    volumes:
    - mongo-volume:/data/db
    labels:
      com.datadoghq.ad.logs: '[{"source":"mongo", "service": "mongo"}]'
volumes:
  mongo-volume:
  horde-storage-volume:
networks:
  network_cache_bridge:
    driver: bridge
