# This is a basic workflow to help you get started with Actions

name: BuildAndDeploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
  push:
    branches: 
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Checkout:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          clean: false

  GenerateFiles:
    needs: Checkout
    runs-on: self-hosted

    steps:
    - name: Generate Files
      run: |
        $ErrorActionPreference = "Stop"
        Set-Location -Path "$env:GITHUB_WORKSPACE"

        $batchFilePath = "C:/UnrealEngine/Engine/Build/BatchFiles/Build.bat"
        if (-Not (Test-Path $batchFilePath)) {
            Write-Host "Build ERROR: The batch file does not appear to be located in the root UE directory. This script must be run from within that directory."
            exit 1
        }

        $batchDir = Split-Path -Path $batchFilePath
        Set-Location -Path $batchDir
        
        $batchFilePath = Join-Path (Get-Location) "Build.bat"
        
        Set-Location -Path "$env:GITHUB_WORKSPACE"

        $projectFilePath = Join-Path (Get-Location) "SProject.uproject"
        try {
            & cmd /c "`"$batchFilePath`" -projectfiles -project=`"$projectFilePath`" -game -engine -progress"
        } catch {
            Write-Error "An error occurred: $_"
            exit 1
        }

  Build:
    needs: [Checkout, GenerateFiles]
    runs-on: self-hosted

    steps:
    - name: Build
      run: |
        $ErrorActionPreference = "Stop"
        Set-Location -Path "$env:GITHUB_WORKSPACE"
        
        $batchFilePath = "C:/UnrealEngine/Engine/Build/BatchFiles/Build.bat"
        if (-Not (Test-Path $batchFilePath)) {
            Write-Host "Build ERROR: The batch file does not appear to be located in the root UE directory. This script must be run from within that directory."
            exit 1
        }

        $batchDir = Split-Path -Path $batchFilePath
        Set-Location -Path $batchDir
        
        $batchFilePath = Join-Path (Get-Location) "Build.bat"
        
        Set-Location -Path "$env:GITHUB_WORKSPACE"

        $projectFilePath = Join-Path (Get-Location) "SProject.uproject"
        try {
            & cmd /c "`"$batchFilePath`" -Target="SProjectEditor Win64 Development -Project="$projectFilePath""
            & cmd /c "`"$batchFilePath`" -Target=`"ShaderCompileWorker Win64 Development -Quiet`" -WaitMutex -FromMsBuild"
            exit $LASTEXITCODE
        } catch {
            Write-Error "An error occurred: $_"
            exit 1
        }

  Clean-up:
    needs: [Build]
    runs-on: self-hosted

    steps:
    - name: Clean-up
      run: |
        $ErrorActionPreference = "Stop"

        $binariesPath = Join-Path (Get-Location).Path "Binaries"
        if (Test-Path $binariesPath) {
        # delete *pdb files
            Get-ChildItem -Path "$binariesPath" -Filter *.pdb -Recurse | Remove-Item -Force
        }

        $pluginsPath = Join-Path (Get-Location).Path "Plugins"
        if (Test-Path $pluginsPath) {
            # delete *pdb files
            Get-ChildItem -Path "$pluginsPath" -Filter *.pdb -Recurse | Remove-Item -Force
        }

  Deploy:
    needs: [Clean-up]
    runs-on: self-hosted

    steps:
    - name: Deploy
      run: | 
        $ErrorActionPreference = "Stop"
        
        Set-Location -Path "$env:GITHUB_WORKSPACE"
        cd ..

        Push-Location -Path "uploader_sproject"
        
        $uploadListPath = Join-Path (Get-Location).Path "uploadList.yaml"
        cmd.exe /c "ncuploader.exe $uploadListPath"
