# This is a basic workflow to help you get started with Actions

name: BuildAndDeploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
  push:
    branches: 
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Checkout:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          clean: false
    
  GenerateTableFiles:
    needs: Checkout
    runs-on: self-hosted
    steps:
      - name: Generate Table Files
        run: |
          $ErrorActionPreference = "Stop"
          Set-Location -Path "$env:GITHUB_WORKSPACE"
          cd ..

          Push-Location -Path "ueproject_generator"

          $configPath = Join-Path (Get-Location).Path "ueproject.yaml"
          cmd.exe /c "ueproject.exe $configPath"
          cmd.exe /c "ncuploader.exe $configPath"

  GenerateFiles:
    needs: GenerateTableFiles
    runs-on: self-hosted
    steps:
    - name: Generate Files
      run: |
        $ErrorActionPreference = "Stop"
        Set-Location -Path "$env:GITHUB_WORKSPACE"

        $ueRoot = "C:/UnrealEngine"
        $batchFilePath = Join-Path $ueRoot "Engine/Build/BatchFiles/Build.bat"
        if (-Not (Test-Path $batchFilePath)) {
            Write-Host "Build ERROR: The batch file does not appear to be located in the root UE directory. This script must be run from within that directory."
            exit 1
        }

        $batchDir = Split-Path -Path $batchFilePath
        Set-Location -Path $batchDir
        
        $batchFilePath = Join-Path (Get-Location) "Build.bat"
        
        Set-Location -Path "$env:GITHUB_WORKSPACE"

        $projectFilePath = Join-Path (Get-Location) "SProject.uproject"
        try {
            & cmd /c "`"$batchFilePath`" -projectfiles -project=`"$projectFilePath`" -game -engine -progress"
        } catch {
            Write-Error "An error occurred: $_"
            exit 1
        }

  Build:
    needs: GenerateFiles
    runs-on: self-hosted
    steps:
    - name: Build
      run: |
        $ErrorActionPreference = "Stop"
        Set-Location -Path "$env:GITHUB_WORKSPACE"
        
        $ueRoot = "C:/UnrealEngine"
        $batchFilePath = Join-Path $ueRoot "Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.exe"
        if (-Not (Test-Path $batchFilePath)) {
            Write-Host "Build ERROR: The batch file does not appear to be located in the root UE directory. This script must be run from within that directory."
            exit 1
        }
        Set-Location -Path "$env:GITHUB_WORKSPACE"

        $projectFilePath = Join-Path (Get-Location) "SProject.uproject"
        try {
            & cmd /c "`"$batchFilePath`" SProjectEditor Win64 Development -project=`"$projectFilePath`" -progress -log"
            exit $LASTEXITCODE
        } catch {
            Write-Error "An error occurred: $_"
            exit 1
        }

  TableCommit:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Table Commit
        run: |
          $ErrorActionPreference = "Stop"
          Set-Location -Path "$env:GITHUB_WORKSPACE"

          git add Source/
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Table files updated"

  Deploy:
    needs: Build
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: | 
        $ErrorActionPreference = "Stop"
        
        Set-Location -Path "$env:GITHUB_WORKSPACE"
        cd ..

        Push-Location -Path "uploader_sproject"
        
        $configPath = Join-Path (Get-Location).Path "uploadList.yaml"
        cmd.exe /c "ncuploader.exe $configPath"


  Cleanup:
    needs: [GenerateTableFiles, GenerateFiles, Build, TableCommit, Deploy]
    if: failure()
    runs-on: self-hosted
    steps:
      - name: Reset Git Changes on Failure
        run: |
          echo "Error! Initializing changes..."
          Set-Location -Path "$env:GITHUB_WORKSPACE"
          git reset --hard
          git clean -fd
